### ISSUE TITLE
A few recommended changes 

### ISSUE THREAD

**Issue by CodeMichaael** [Jbablestime/M-Terminal#1]
For performance it would help to use async before any external requests and to log actions with logging. Just a few tips

**Comment by Jbablestime** [comment]
Hello Michael (Mixe),

As this is in beta kind of, I have added better handling when it comes to
making 3rd party requests outside of the program and what it needs to run.
Currently it's being re-coded all together, adding newer stuff as well as
better error handling and all that. I do not plan to allow this application
to run without wifi, so using async wouldn't matter.

Thank you for your feedback, if you have any more please feel free to email
me at ***@***.***

Thank you,
Jb
